### ISSUE TITLE
Changer le type d'une annotation

### ISSUE THREAD

**Issue by Ericdsr** [jblavisse/scriptalium#11]
# Tâche : Changer le type d'une annotation

Permettre à l'utilisateur de modifier le type d'une annotation après sa création

## Détails : 
- [ ]  [Ajouter une option pour changer le type d'une annotation (Texte, Image, Vidéo, Son)]
- [ ]  [Adapter l'interface en fonction du type sélectionné]
- [ ]  [Tester le changement de type]

**Comment by jblavisse** [comment]
# Task: **Specify** the Type of an Annotation

Allow the user to specify the type of an annotation when creating it, and display the type in the annotation details.

## Details:

- [ ] **Add an option to specify the type of an annotation**:
  - Provide a dropdown or selection menu that allows the user to choose the type of annotation.
  - Available types should include:
    - [ ] Text
    - [ ] Image
    - [ ] Video
    - [ ] Audio


- [ ] **Update the display of the annotation in the list**:
  - When displaying annotations (in a tooltip, pop-up, or list), include the type of the annotation with an icon.
  
- [ ] **Test the annotation type functionality**:
  - Ensure that the interface adapts correctly for each type.
  - Verify that the annotation type is correctly displayed in the list or pop-up after creation.
