### ISSUE TITLE
Voir l'annotation ajoutée

### ISSUE THREAD

**Issue by Ericdsr** [jblavisse/scriptalium#7]
# Tâche : Voir l'annotation ajoutée

Permettre l'affichage des détails d'une annotation ajoutée au texte

## Détails : 
- [ ]  [Afficher les détails d'une annotation ajoutée au survol ou au clic sur la partie du texte annotée.]
- [ ]  [Gérer l'affichage des détails lorsque plusieurs annotations sont présentes]

**Comment by jblavisse** [comment]
# Task: View Added Annotation

Enable the display of detailed information for annotations that have been added to selected portions of the text in the Markdown editor.

## Details:

- [ ] **Display annotation details on hover or click**:
  - When the user hovers over or clicks on an annotated section of the text, a tooltip or pop-up should appear showing the details of the annotation.
  - The details should include:
    - [ ] The title of the annotation.

- [ ] **Test interactions for viewing annotations**:
  - Test the display of annotations when hovering over both short and long sections of annotated text.
  - Ensure that the pop-up or tooltip appears correctly for all lengths of text.
  - Verify that the annotation title is clearly displayed and readable.
